### ISSUE TITLE
GPU usage when running demo code - low fps

### ISSUE THREAD

**Issue by SonNguyen2510** [Vegetebird/StridedTransformer-Pose3D#15]
Dear author,

Thank you for your amazing work. 
I trying run your demo code with in-the-wild video and I got only about 15fps with 3D pose estimation (with HRnet and yolo detection) on my RTX3090 GPU.
I checked gpu usage and it use only about 2GB of my memory. I want to ask that is there any setting that limmit my gpu usage and anyway to increase fps when running demo? I have install CUDA 11.x already. According to the paper, the method can achieve real-time application. Am I doing wrong some where? sorry, I'm new to this deeplearning field.
Thank you very much for your time!

**Comment by Vegetebird** [comment]
In our demo code, we plot the joints, which is time-consuming. Without visualization, our model is real-time.

**Comment by SonNguyen2510** [comment]
@Vegetebird I guess It is real-tine only when you inference 3D model alone right? When I try to use 2D pose in combination with 3D pose without visualization, it cannot achieve realtime
