### ISSUE TITLE
how to use 27 frames

### ISSUE THREAD

**Issue by parkjin0903** [Vegetebird/StridedTransformer-Pose3D#17]
Thank you for providing the inference code. I am very interested in your paper.
According to the paper and code, it seems like using 351 frames apparently. I tried to modify vis.py code to use 27 frames.  Unfortunately I faced a hardship. The following is the error code that I got. Could you give me a instruction?

-------------------------

size mismatch for Transformer.pos_embedding: copying a param with shape torch.Size([1, 351, 256]) from checkpoint, the shape in current model is torch.Size([1, 27, 256]).
	size mismatch for Transformer_reduce.model.pos_embedding_1: copying a param with shape torch.Size([1, 351, 256]) from checkpoint, the shape in current model is torch.Size([1, 27, 256]).
	size mismatch for Transformer_reduce.model.pos_embedding_2: copying a param with shape torch.Size([1, 351, 256]) from checkpoint, the shape in current model is torch.Size([1, 27, 256]).
	size mismatch for Transformer_reduce.model.pos_embedding_3: copying a param with shape torch.Size([1, 351, 256]) from checkpoint, the shape in current model is torch.Size([1, 27, 256]).

**Comment by SonNguyen2510** [comment]
You need to retrain the model using 27 frames yourself first then using that model for your purpose.

**Comment by Vegetebird** [comment]
@SonNguyen2510 is right

**Comment by parkjin0903** [comment]
Thank you !
