### ISSUE TITLE
Back projection

### ISSUE THREAD

**Issue by iulsko** [Vegetebird/StridedTransformer-Pose3D#18]
is there a way to back-project estimated 3D points back onto the image?

**Comment by Vegetebird** [comment]
You can refer to "https://github.com/facebookresearch/VideoPose3D/blob/1afb1ca0f1237776518469876342fc8669d3f6a9/run.py#L373"

**Comment by iulsko** [comment]
@Vegetebird hi Wenhao, yes, I have been referring to this bit but since `output_3D` in [here](https://github.com/Vegetebird/StridedTransformer-Pose3D/blob/9d988ac54234c5acc6a67ae746ce5bdbea204f8a/demo/vis.py#L201) is given in relative 3D coordinates (relative to the root) and not in camera 3D coordinates, the back projections do not work.

is there any way i can bring `output_3D` to camera 3D frame?

**Comment by iulsko** [comment]
@Vegetebird so I assume it is not possible for "in-the-wild" videos, since I do not have gt_3D?

**Comment by Vegetebird** [comment]
Yeah, and we do not have the camera parameter to perform projection

**Comment by iulsko** [comment]
@Vegetebird again, just to confirm: so we only have 3D movements in the "relative" coordinate frame. 
e.g. without the camera parameters we are also not able to find the absolute movement in mm/cm/m?

**Comment by Vegetebird** [comment]
Our method can not find the absolute movement, but you can refer to (VideoPose3D)[https://github.com/facebookresearch/VideoPose3D] to train a Trajectory model to get the Global positions.
