### ISSUE TITLE
About visualization

### ISSUE THREAD

**Issue by miraito-wa** [Vegetebird/StridedTransformer-Pose3D#2]
Hello, I am very interested in your work, but I have not been successful in trying to use a general visualization method. Could you please provide the visualization code?

**Comment by Vegetebird** [comment]
You can refer to “[https://github.com/facebookresearch/VideoPose3D”](https://github.com/facebookresearch/VideoPose3D%E2%80%9D) to visualize the results.

**Comment by Vegetebird** [comment]
Hi~ @miraito-wa 
We have released the demo and in-the-wild inference code. Plaese download the latest repo and refer to [demo](https://github.com/Vegetebird/StridedTransformer-Pose3D#demo).
