### ISSUE TITLE
PyTorch error

### ISSUE THREAD

**Issue by Adithya2907** [Vegetebird/StridedTransformer-Pose3D#24]
I get the following error when I try to train the model using:
`python main.py --test --refine --reload --refine_reload --previous_dir checkpoint/pretrained`

`AttributeError: 'list' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.`

I'm using Google Colab, with CUDA version of 11.2 and PyTorch version of 1.12, Python version 3.7

**Comment by Vegetebird** [comment]
Please check whether the pretrained model is in the "checkpoint/pretrained"
