### ISSUE TITLE
Reloading a .pth file 

### ISSUE THREAD

**Issue by harish-prakash-99** [Vegetebird/StridedTransformer-Pose3D#26]
Wonderful work! I just noticed this teeny-tiny error, in main.py < line 175< refine_path object initialize as a list (While it needn't be). This causes the following error: 

<img width="988" alt="Screen Shot 2022-11-22 at 4 09 32 PM" src="https://user-images.githubusercontent.com/55242672/203421891-037fdbe3-bcfe-43e6-88fc-48276cca89a3.png">

So, either line 175 should be removed or line 178 should become "refine_path.append(path)", which may cause further downstream errors due to refine_path being a list. Please check that out! 

Thanks!

**Comment by Vegetebird** [comment]
Thanks for pointing out that. We have fixed it.
