### ISSUE TITLE
Demo Error: vis.py empty kepoints and scores

### ISSUE THREAD

**Issue by aytekXR** [Vegetebird/StridedTransformer-Pose3D#29]
Hi, great work! Thank you all, 

I have a problem with the demo/vis.py code. When I run the file with default parameters with provided sample video. I get empty keypoints and scores. As shown in the screen shot. I tried to debug, but could not resolve the problem. Can you help? Thanks in advance !

![Screenshot from 2023-01-05 21-51-47](https://user-images.githubusercontent.com/62661118/210858099-8d72cdd0-0fee-4942-81a5-1d9d3f7ceada.png)

**Comment by Vegetebird** [comment]
I use the released code and it works well. Maybe you can try "pip install pillow --upgrade"

**Comment by aytekXR** [comment]
I have solved the problem. As argument, i used only the name of the video, not the path of the video. So, my problem was with argument parser.

Thank you for your interest.

'''
python demo/vis.py --video sample_video.mp4
'''
