### ISSUE TITLE
ValueError: axes don't match array

### ISSUE THREAD

**Issue by efgagfecdb** [Vegetebird/StridedTransformer-Pose3D#30]
hi, first of all thanks million for sharing us this great work. 
in fact, I'm stuck with ValueError while trying Demo with my videos.
(+ same error raised with your sample_video.mp4)
some advice would be grateful.

error information below...

$ python demo/vis.py --video test2.mp4

>>
Generating 2D pose...
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "demo/vis.py", line 275, in <module>
    get_pose2D(video_path, output_dir)
  File "demo/vis.py", line 86, in get_pose2D
    keypoints, scores = hrnet_pose(video_path, det_dim=416, num_peroson=1, gen_output=True)
  File "/home/seo/workspace/StridedTransformer-Pose3D/demo/lib/hrnet/gen_kpts.py", line 163, in gen_video_kpts
    keypoints = keypoints.transpose(1, 0, 2, 3)  # (T, M, N, 2) --> (M, T, N, 2)
ValueError: axes don't match array

**Comment by Vegetebird** [comment]
Could you run the ' sample_video.mp4' well? I use the released code and it works well.

**Comment by efgagfecdb** [comment]
I think there's some mistake in Dependency.
as I tried with python3.7. everything worked fine.

thanks againg
