### ISSUE TITLE
The meaning of "p1" and "p2" in the training log

### ISSUE THREAD

**Issue by wwwpkol** [Vegetebird/StridedTransformer-Pose3D#31]
Thank you for your excellent code, do "p1" and "p2" in the training log represent the values of "Protocol #1" (MPJPE) and "Protocol #2" (P-MPJPE) in the paper?
![image](https://user-images.githubusercontent.com/50726523/218999802-4260b26f-619d-46ed-8025-737e7672987b.png)

**Comment by Vegetebird** [comment]
Yes~

**Comment by wwwpkol** [comment]
Thank you for your generous answer！
