### ISSUE TITLE
How to get MPJVE result?

### ISSUE THREAD

**Issue by TomCatOnline** [Vegetebird/StridedTransformer-Pose3D#33]
Thank you for your great job!
but how can i get MPJVE results while testing the model?
btw whats the unit of MPJVE? is it mm?

**Comment by Vegetebird** [comment]
We use their code to get the MPJVE results https://github.com/facebookresearch/VideoPose3D/blob/1afb1ca0f1237776518469876342fc8669d3f6a9/run.py#L704. 
The unit of MPJVE is mm.
