### ISSUE TITLE
Problem in reloading the model in demo.py

### ISSUE THREAD

**Issue by Hanaba133133** [Vegetebird/StridedTransformer-Pose3D#36]
Hi, thanks for your brilliant work. I have some trouble when running demo.py. The log is as follow:

  File "F:/StridedTransformer-Pose3D-main/demo/vis.py", line 143, in get_pose3D
    model_dict[name] = pre_dict[name]
KeyError: 'encoder.0.weight'

I found the index of model_dict and pre_dict is not match. The model_dict is: 
['encoder.0.weight', 'encoder.0.bias', 'encoder.1.weight', 'encoder.1.bias', 'encoder.1.running_mean', 'encoder.1.running_var', 'encoder.1.num_batches_tracked', 'Transformer.pos_embedding', 'Transformer.model.layers.0.self_attn.linears.0.weight', 'Transformer.model.layers.0.self_attn.linears.0.bias', 'Transformer.model.layers.0.self_attn.linears.1.weight', 'Transformer.model.layers.0.self_attn.linears.1.bias', 'Transformer.model.layers.0.self_attn.linears.2.weight', 'Transformer.model.layers.0.self_attn.linears.2.bias', 'Transformer.model.layers.0.self_attn.linears.3.weight', 'Transformer.model.layers.0.self_attn.linears.3.bias', 'Transformer.model.layers.0.feed_forward.w_1.weight', 'Transformer.model.layers.0.feed_forward.w_1.bias', 'Transformer.model.layers.0.feed_forward.w_2.weight', .....]

 and the model_dict is:
['conv1.weight', 'bn1.weight', 'bn1.bias', 'bn1.running_mean', 'bn1.running_var', 'bn1.num_batches_tracked', 'conv2.weight', 'bn2.weight', 'bn2.bias', 'bn2.running_mean', 'bn2.running_var', 'bn2.num_batches_tracked', 'layer1.0.conv1.weight', 'layer1.0.bn1.weight', 'layer1.0.bn1.bias', 'layer1.0.bn1.running_mean', 'layer1.0.bn1.running_var', 'layer1.0.bn1.num_batches_tracked', 'layer1.0.conv2.weight', 'layer1.0.bn2.weight', 'layer1.0.bn2.bias', 'layer1.0.bn2.running_mean', 'layer1.0.bn2.running_var', 'layer1.0.bn2.num_batches_tracked', 'layer1.0.conv3.weight', 'layer1.0.bn3.weight', 'layer1.0.bn3.bias', 'layer1.0.bn3.running_mean', 'layer1.0.bn3.running_var', 'layer1.0.bn3.num_batches_tracked', '...]

It would be very grateful if you can help me to fix it.

**Comment by Vegetebird** [comment]
You could try downloading our latest repository and pre-trained models.
