### ISSUE TITLE
 How to use ground truth 2D joint locations as input in the code?

### ISSUE THREAD

**Issue by zhang-yuxian** [Vegetebird/StridedTransformer-Pose3D#38]
How to use ground truth 2D joint locations as input in the code?
<img width="803" alt="屏幕截图 2023-12-14 210017" src="https://github.com/Vegetebird/StridedTransformer-Pose3D/assets/112807157/a3813ab0-58ac-4668-8bcc-416f96d57c75">

**Comment by Vegetebird** [comment]
Hi~ You can use the command: --keypoints 'gt'

**Comment by zhang-yuxian** [comment]
Thank you! I have successfully solved this problem.

---- Replied Message ----
| From | Wenhao ***@***.***> |
| Date | 12/15/2023 21:15 |
| To | Vegetebird/StridedTransformer-Pose3D ***@***.***> |
| Cc | zhang-yuxian ***@***.***>,
Author ***@***.***> |
| Subject | Re: [Vegetebird/StridedTransformer-Pose3D] How to use ground truth 2D joint locations as input in the code? (Issue #38) |

Hi~ You can use the command: --keypoints 'gt'

**Comment by cqs0925** [comment]
Hey, thanks for your code. I've tried using the pretrained model. Fine-tuned CPN gives the exact same result, but ground truth input only gives 37.31/30.03(Protocol 1/2)  while in the paper it is 28.5 under protocol 1. I've tried to test without refine module and cpn give even better result than gt. I've tried this code twice and it gives the same problem. I am wondering is there another pretrained model that are used to process GT input.

**Comment by zhang-yuxian** [comment]
For ground truth as input, change "self.parser.add_argument('-k', '--keypoints', default='cpn_ft_h36m_dbb', type=str)"  to  "self.parser.add_argument('-k', '--keypoints', default='gt', type=str)",  then train and test. 
If you get worse results than this paper, please check "frames(351)" and "batch_size". Actually, Increasing “batch_size” value can reduce MPJPE, like  “batch_size=280”/“batch_size=300”....but it requires larger graphics memory！Please try again!









在 2024-01-24 20:12:50，"cqs0925" ***@***.***> 写道：

Hey, thanks for your code. I've tried using the pretrained model. Fine-tuned CPN gives the exact same result, but ground truth input only gives 37.31/30.03(Protocol 1/2) while in the paper it is 28.5 under protocol 1. I've tried to test without refine module and cpn give even better result than gt. I've tried this code twice and it gives the same problem. I am wondering is there another pretrained model that are used to process GT input.
