### ISSUE TITLE
How to calculate FLOPs(G)  and  Param(M) in the code?

### ISSUE THREAD

**Issue by zhang-yuxian** [Vegetebird/StridedTransformer-Pose3D#39]
I used the ptflops library to calculate FLOPs and Param, but the FLOPs values differ significantly from the paper. So how do I calculate the FLOPs(G)  and  Param(M) in the code?
<img width="524" alt="屏幕截图 2023-12-16 212315" src="https://github.com/Vegetebird/StridedTransformer-Pose3D/assets/112807157/5ce2bc77-473e-441c-ad28-d0780a05eeff">

**Comment by Vegetebird** [comment]
We calculate the FLOPs manually. You could consider using thop package for calculation.
