### ISSUE TITLE
Training log for cpn detections?

### ISSUE THREAD

**Issue by alecda573** [Vegetebird/StridedTransformer-Pose3D#4]
Are you able to provide the training logs your 27 and 81 frame models using cpn detections?

**Comment by Vegetebird** [comment]
Hi~I'm sorry for the late reply.

This is my latest log of 27 frame using cpn detections:
2021/06/16 19:50:49 epoch: 1, lr: 0.0010000, loss: 0.1281, MPJPE: 65.31, p1: 52.87, p2: 41.01
2021/06/16 20:07:50 epoch: 2, lr: 0.0009500, loss: 0.0907, MPJPE: 47.93, p1: 52.30, p2: 40.25
2021/06/16 20:27:35 epoch: 3, lr: 0.0009025, loss: 0.0832, MPJPE: 44.61, p1: 50.64, p2: 39.74
2021/06/16 20:44:51 epoch: 4, lr: 0.0008574, loss: 0.0793, MPJPE: 42.86, p1: 50.31, p2: 38.91
2021/06/16 21:05:46 epoch: 5, lr: 0.0008145, loss: 0.0768, MPJPE: 41.73, p1: 50.49, p2: 39.08
2021/06/16 21:24:37 epoch: 6, lr: 0.0004073, loss: 0.0734, MPJPE: 40.21, p1: 49.09, p2: 38.29
2021/06/16 21:43:54 epoch: 7, lr: 0.0003869, loss: 0.0726, MPJPE: 39.82, p1: 49.27, p2: 38.64
2021/06/16 22:03:34 epoch: 8, lr: 0.0003675, loss: 0.0718, MPJPE: 39.44, p1: 49.18, p2: 38.33
2021/06/16 22:20:41 epoch: 9, lr: 0.0003492, loss: 0.0712, MPJPE: 39.17, p1: 49.15, p2: 38.28
2021/06/16 22:38:33 epoch: 10, lr: 0.0003317, loss: 0.0707, MPJPE: 38.96, p1: 48.57, p2: 38.19
2021/06/16 22:55:27 epoch: 11, lr: 0.0001659, loss: 0.0694, MPJPE: 38.36, p1: 49.34, p2: 38.37
2021/06/16 23:14:11 epoch: 12, lr: 0.0001576, loss: 0.0692, MPJPE: 38.28, p1: 49.15, p2: 38.34
2021/06/16 23:31:17 epoch: 13, lr: 0.0001497, loss: 0.0689, MPJPE: 38.17, p1: 49.25, p2: 38.49
2021/06/16 23:48:42 epoch: 14, lr: 0.0001422, loss: 0.0688, MPJPE: 38.08, p1: 49.03, p2: 38.50

And adding a refine module:
2021/06/17 01:06:20 epoch: 1, lr: 0.0000100, loss: 0.0268, MPJPE: 26.85, p1: 47.11, p2: 37.80
2021/06/17 01:28:48 epoch: 2, lr: 0.0000095, loss: 0.0264, MPJPE: 26.39, p1: 47.20, p2: 37.78
2021/06/17 01:51:19 epoch: 3, lr: 0.0000090, loss: 0.0262, MPJPE: 26.19, p1: 47.38, p2: 37.88
2021/06/17 02:13:58 epoch: 4, lr: 0.0000086, loss: 0.0260, MPJPE: 26.05, p1: 47.24, p2: 37.78
2021/06/17 02:36:33 epoch: 5, lr: 0.0000081, loss: 0.0259, MPJPE: 25.93, p1: 47.16, p2: 37.72
2021/06/17 02:59:13 epoch: 6, lr: 0.0000041, loss: 0.0259, MPJPE: 25.87, p1: 47.18, p2: 37.76
2021/06/17 03:19:51 epoch: 7, lr: 0.0000039, loss: 0.0258, MPJPE: 25.81, p1: 47.16, p2: 37.84
2021/06/17 03:36:34 epoch: 8, lr: 0.0000037, loss: 0.0258, MPJPE: 25.76, p1: 47.10, p2: 37.70
2021/06/17 03:53:12 epoch: 9, lr: 0.0000035, loss: 0.0257, MPJPE: 25.72, p1: 47.10, p2: 37.75
2021/06/17 04:10:05 epoch: 10, lr: 0.0000033, loss: 0.0257, MPJPE: 25.71, p1: 47.28, p2: 37.81
2021/06/17 04:26:57 epoch: 11, lr: 0.0000017, loss: 0.0256, MPJPE: 25.64, p1: 47.11, p2: 37.68
2021/06/17 04:43:40 epoch: 12, lr: 0.0000016, loss: 0.0257, MPJPE: 25.67, p1: 47.09, p2: 37.71
2021/06/17 05:00:21 epoch: 13, lr: 0.0000015, loss: 0.0256, MPJPE: 25.64, p1: 47.21, p2: 37.79
2021/06/17 05:15:32 epoch: 14, lr: 0.0000014, loss: 0.0256, MPJPE: 25.64, p1: 47.23, p2: 37.82

**Comment by alecda573** [comment]
@Vegetebird  can you provide any training logs for your models with a larger temporal window?

**Comment by Vegetebird** [comment]
Hi~This is my training log with 351 frames using cpn detections:
2021/11/20 22:40:51 epoch: 1, lr: 0.0010000, loss: 0.1157, MPJPE: 58.48, p1: 49.62, p2: 38.91
2021/11/21 00:03:24 epoch: 2, lr: 0.0009500, loss: 0.0774, MPJPE: 40.68, p1: 48.03, p2: 37.52
2021/11/21 01:26:00 epoch: 3, lr: 0.0009025, loss: 0.0707, MPJPE: 37.62, p1: 46.69, p2: 36.74
2021/11/21 02:48:49 epoch: 4, lr: 0.0008574, loss: 0.0674, MPJPE: 36.10, p1: 46.26, p2: 36.33
2021/11/21 04:11:27 epoch: 5, lr: 0.0008145, loss: 0.0653, MPJPE: 35.11, p1: 45.27, p2: 35.67
2021/11/21 05:33:59 epoch: 6, lr: 0.0004073, loss: 0.0624, MPJPE: 33.86, p1: 45.82, p2: 36.12
2021/11/21 06:56:34 epoch: 7, lr: 0.0003869, loss: 0.0618, MPJPE: 33.54, p1: 45.66, p2: 36.00
2021/11/21 08:19:07 epoch: 8, lr: 0.0003675, loss: 0.0612, MPJPE: 33.26, p1: 45.56, p2: 35.84
2021/11/21 09:41:41 epoch: 9, lr: 0.0003492, loss: 0.0607, MPJPE: 33.03, p1: 45.51, p2: 35.98
2021/11/21 11:04:13 epoch: 10, lr: 0.0003317, loss: 0.0604, MPJPE: 32.86, p1: 45.54, p2: 36.25
2021/11/21 12:26:57 epoch: 11, lr: 0.0001659, loss: 0.0594, MPJPE: 32.46, p1: 45.53, p2: 35.95
2021/11/21 13:49:27 epoch: 12, lr: 0.0001576, loss: 0.0592, MPJPE: 32.37, p1: 45.42, p2: 36.03
2021/11/21 15:12:06 epoch: 13, lr: 0.0001497, loss: 0.0591, MPJPE: 32.28, p1: 45.63, p2: 36.13
2021/11/21 16:34:41 epoch: 14, lr: 0.0001422, loss: 0.0588, MPJPE: 32.19, p1: 45.47, p2: 36.09
2021/11/21 17:57:16 epoch: 15, lr: 0.0001351, loss: 0.0587, MPJPE: 32.13, p1: 45.36, p2: 35.97
2021/11/21 19:19:51 epoch: 16, lr: 0.0000675, loss: 0.0583, MPJPE: 31.95, p1: 45.19, p2: 35.94
2021/11/21 20:42:26 epoch: 17, lr: 0.0000642, loss: 0.0582, MPJPE: 31.91, p1: 45.54, p2: 35.98
2021/11/21 22:04:57 epoch: 18, lr: 0.0000610, loss: 0.0582, MPJPE: 31.90, p1: 45.52, p2: 36.01
2021/11/21 23:27:34 epoch: 19, lr: 0.0000579, loss: 0.0581, MPJPE: 31.85, p1: 45.34, p2: 36.01

And adding a refine module:
2021/11/21 10:10:10 epoch: 1, lr: 0.0000100, loss: 0.0241, MPJPE: 24.09, p1: 43.71, p2: 35.24
2021/11/21 11:33:42 epoch: 2, lr: 0.0000095, loss: 0.0235, MPJPE: 23.52, p1: 43.81, p2: 35.23
2021/11/21 12:57:19 epoch: 3, lr: 0.0000090, loss: 0.0233, MPJPE: 23.25, p1: 43.78, p2: 35.31
2021/11/21 14:21:08 epoch: 4, lr: 0.0000086, loss: 0.0231, MPJPE: 23.09, p1: 43.69, p2: 35.27
2021/11/21 15:44:42 epoch: 5, lr: 0.0000081, loss: 0.0230, MPJPE: 22.95, p1: 43.67, p2: 35.22
2021/11/21 17:08:15 epoch: 6, lr: 0.0000041, loss: 0.0229, MPJPE: 22.85, p1: 43.78, p2: 35.36
2021/11/21 18:31:52 epoch: 7, lr: 0.0000039, loss: 0.0228, MPJPE: 22.81, p1: 43.76, p2: 35.25
2021/11/21 19:55:29 epoch: 8, lr: 0.0000037, loss: 0.0227, MPJPE: 22.72, p1: 43.77, p2: 35.28
2021/11/21 21:18:58 epoch: 9, lr: 0.0000035, loss: 0.0227, MPJPE: 22.72, p1: 43.66, p2: 35.21
2021/11/21 22:42:22 epoch: 10, lr: 0.0000033, loss: 0.0227, MPJPE: 22.69, p1: 43.79, p2: 35.30
