### ISSUE TITLE
How to  conducted experimental calculation on HumanEva-I based on Mask R-CNN 2D detections and 2D ground truth？

### ISSUE THREAD

**Issue by zhang-yuxian** [Vegetebird/StridedTransformer-Pose3D#41]
How to calculate the evaluation results in the table？
<img width="397" alt="屏幕截图 2023-12-16 213541" src="https://github.com/Vegetebird/StridedTransformer-Pose3D/assets/112807157/820ec13d-999a-41b2-999f-a975170ac6bf">

**Comment by Vegetebird** [comment]
We use their code (https://github.com/facebookresearch/VideoPose3D/tree/main) to conduct experiments on HumanEva-I .
