### ISSUE TITLE
how can i get the attention map in the article

### ISSUE THREAD

**Issue by sayoko17** [Vegetebird/StridedTransformer-Pose3D#42]
[StridedTransformer-Pose3D](https://github.com/Vegetebird/StridedTransformer-Pose3D/tree/main)/[common](https://github.com/Vegetebird/StridedTransformer-Pose3D/tree/main/common)
/plot_att.py
i learned about it but i don't understand the code about data_names = sorted(glob.glob(os.path.join('data/', '*.npz'))) ,and i can’t get the attention map in the article

**Comment by Vegetebird** [comment]
You need to run the model and save the [p_attn](https://github.com/Vegetebird/StridedTransformer-Pose3D/blob/6d30838f47d7d10c8aa1dc6db5f350bc8bdddb26/model/block/vanilla_transformer_encoder.py#L42) as an npz file.
