### ISSUE TITLE
Hello, may I ask you a question? This algorithm can process real-time video streams

### ISSUE THREAD

**Issue by wuxiaolianggit** [Vegetebird/StridedTransformer-Pose3D#6]
Hello, may I ask you a question? This algorithm can process real-time video streams？ @Vegetebird

**Comment by Vegetebird** [comment]
Our method outputs the center frame's 3D posed from a input video. 

In real-time applications, the "causal setting", mentioned in [1], is more appropriate, i.e, it takes a video sequence as input and outputs the pose of the final frame. 

Our algorithm also can be trained in this "causal setting".  

[1] Pavllo, et al. 3D human pose estimation in video with temporal convolutions and semi-supervised training, CVPR 2019.

**Comment by Allencheng97** [comment]
Hi, May I ask how to your algorithm in casual setting?
