### ISSUE TITLE
hello,  I want to ask one question. When I run demo.py, I met this question as below. How can I fix it

### ISSUE THREAD

**Issue by shoupmao** [Vegetebird/StridedTransformer-Pose3D#8]
![2022-06-07 14-34-21屏幕截图](https://user-images.githubusercontent.com/94581598/172311943-0e280b85-ad2f-451a-b285-f2df0c25f3c2.png)

**Comment by Vegetebird** [comment]
Please check the StridedTransformer's pretrained model is in the 'checkpoint/pretrained'.
